### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by JusticeBond** [xkik-dev/XKik#16]
Xkik is not working for me? What should I do?

**Comment by JusticeBond** [comment]
I'm on the Kik version that is suitable with the current xkik but it doesn't seem to work, the only feature that works is read. And the Kik app crashes when I hold the settings icon

**Comment by alroy214** [comment]
That is cause the settings button uses resources from the Xkik, what version of sdk are you using?
Remember xpose on 24/25 isn't stable so the resource doesn't always latch properly, if you are using those versions when it will be an official xpose for those programs the app will work properly.

**Comment by xkik-dev** [comment]
XKik is not fully compatible with Nougat yet, if that's what you are using it on.

**Comment by JusticeBond** [comment]
I'm on nougat and also on xposed SDK 25 but I think xposed has been officially released on nougat too recently.

**Comment by JusticeBond** [comment]
After updating to official Xposed framework (SDK 25)for nougat, xkik is working perfectly fine. Thanks for the help!
