### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by sasurichulli** [xkik-dev/XKik#18]
xkik app force closes if I select anything other than xkik main or licenses

**Comment by xkik-dev** [comment]
Your config file is corrupted. Delete the file at /sdcard/xkik/config.json
I'm working on fixing this issue, but haven't had a lot of time lately.

**Comment by sasurichulli** [comment]
I figured it out before you replied. Deleted the whole xkik folder and reinstalled xkik and it worked. Thanks anyways!
