### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by DKnightX91** [xkik-dev/XKik#5]
When dark mode is turned on opening a chat will crash the Kik.

**Comment by xkik-dev** [comment]
I'll look into this - Thanks for letting me know

**Comment by xkik-dev** [comment]
I can't seem to reproduce this bug, it works fine for me. Are you on the latest XKik and on a compatible kik version?

**Comment by DKnightX91** [comment]
Kik is 11.26.0.16889 and with the latest version of XKik.

**Comment by xkik-dev** [comment]
Is it possible that you can provide kik's crash message by posting the appropriate logcat messages? I suggest using an app like [aLogcat](https://play.google.com/store/apps/details?id=rs.pedjaapps.alogcatroot.app)
Reproduce the crash in Kik, then go to your logcat app and search for "kik.android", copy/screenshot what appears there and post it here

**Comment by DKnightX91** [comment]
Hey got it to work again. Needed to clear kiks cache
