### ISSUE TITLE
Improvement: Disable "Who's Reading" when inside chat

### ISSUE THREAD

**Issue by NLDev** [xkik-dev/XKik#7]
This feature is quite useful if Kik is in the background or you're chatting inside a group chat. 

However in private chats it gets pretty annoying when seeing this message on each message.
Since you are already inside the chat and are able to see directly if the message has been read. 

Just an improvement idea. No bug.

**Comment by xkik-dev** [comment]
I'll see what I can do about it. Thank you for the suggestion :)

**Comment by NLDev** [comment]
Thanks! Great module by the way :)

**Comment by xkik-dev** [comment]
Just an update on this issue, this is coming in the next update
![image](https://user-images.githubusercontent.com/28283142/30568120-603c50b4-9c88-11e7-87c7-51b05a8676f6.png)

**Comment by xkik-dev** [comment]
Up on the latest update

**Comment by NLDev** [comment]
Awesome, thank you! :smiley:
